import { ProductType } from "./store";

export const SAMPLE_PRODUCTS: ProductType[] = [
  {
    id: "raib-tote-01",
    name: "The Royal Crimson Italian Leather Tote",
    nameBn: "রয়েল ক্রিমসন ইতালিয়ান লেদার টোট ব্যাগ",
    price: 4850,
    originalPrice: 6200,
    category: "Tote Bags",
    color: "Crimson Red",
    material: "100% Full-Grain Calfskin Leather",
    image: "/tote_bag_red_1786395433017.jpg",
    secondaryImage: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80",
    description: "Handcrafted in Florence using vegetable-tanned Italian leather. Featuring spacious triple compartment interior, 18K gold palladium hardware, and removable shoulder strap.",
    descriptionBn: "ফ্লোরেন্সে তৈরি খাঁটি ইতালিয়ান কালফস্কিন লেদার ব্যাগ। এতে রয়েছে ট্রিপল কম্পার্টমেন্ট, ১৮K গোল্ডেন পলেস্টার হার্ডওয়্যার এবং অ্যাডজাস্টেবল শোল্ডার স্ট্র্যাপ।",
    rating: 4.9,
    reviewCount: 42,
    isNewArrival: true,
    isBestSeller: true,
    dimensions: "34cm x 26cm x 14cm (Fits 13-inch MacBook & iPad)"
  },
  {
    id: "raib-crossbody-02",
    name: "Obsidian Quilted Chain Crossbody Bag",
    nameBn: "অবসিডিয়ান কুইল্টেড চেইন ক্রসবডি ব্যাগ",
    price: 3950,
    originalPrice: 4800,
    category: "Crossbody Bags",
    color: "Classic Black",
    material: "Soft Nappa Leather",
    image: "/crossbody_black_1786395824801.jpg",
    secondaryImage: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&auto=format&fit=crop&q=80",
    description: "An iconic evening and day staple with chevron diamond quilting, gold chain sliding strap, magnetic snap closure, and silk interior lining.",
    descriptionBn: "শেভরন ডায়মন্ড কুইল্টিং নকশায় তৈরি বিলাসবহুল ক্রসবডি ব্যাগ। সাথে রয়েছে ১৮K গোল্ড মেটালিক চেইন ও সফট সিল্ক লাইনিং।",
    rating: 4.8,
    reviewCount: 38,
    isNewArrival: true,
    isBestSeller: true,
    dimensions: "24cm x 16cm x 8cm"
  },
  {
    id: "raib-shoulder-03",
    name: "Minimalist Nude Taupe Leather Shoulder Bag",
    nameBn: "মিনিমালিস্ট ন্যুড টোপ লেদার শোল্ডার ব্যাগ",
    price: 3600,
    originalPrice: 4200,
    category: "Shoulder Bags",
    color: "Beige / Taupe",
    material: "Saffiano Genuine Leather",
    image: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800&auto=format&fit=crop&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1591561954557-26941169b49e?w=800&auto=format&fit=crop&q=80",
    description: "Sculptural silhouette with sleek curved lines, hidden magnetic flap, interior zip pocket, and water-resistant Saffiano finish.",
    descriptionBn: "আধুনিক নান্দনিক ডিজাইনের স্কার্পচারাল শোল্ডার ব্যাগ। ওয়াটার-রেজিস্ট্যান্ট সাফিয়ানো লেদার ও গোপন ম্যাগনেটিক লক।",
    rating: 4.7,
    reviewCount: 29,
    isNewArrival: false,
    isBestSeller: true,
    dimensions: "28cm x 18cm x 7cm"
  },
  {
    id: "raib-clutch-04",
    name: "Emerald Empress Velvet Evening Clutch",
    nameBn: "এমেরাল্ড এমপ্রেস ভেলভেট ইভনিং ক্লাচ",
    price: 2950,
    originalPrice: 3500,
    category: "Clutches & Evening",
    color: "Emerald Green",
    material: "Premium Velvet & Brass Frame",
    image: "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=800&auto=format&fit=crop&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&auto=format&fit=crop&q=80",
    description: "Showstopping evening handbag crafted from rich emerald silk velvet with crystal clasp and detachable thin gold chain.",
    descriptionBn: "পার্টি ও জমকালো আয়োজনের জন্য সিল্ক ভেলভেট ও জুয়েলারি ক্রিস্টাল লক ক্লাচ ব্যাগ। সাথে চেইন স্ট্র্যাপ।",
    rating: 5.0,
    reviewCount: 19,
    isNewArrival: true,
    isBestSeller: false,
    dimensions: "20cm x 12cm x 5cm"
  },
  {
    id: "raib-mini-05",
    name: "Monogram Pure White Structured Mini Bag",
    nameBn: "মনোগ্রাম পিওর হোয়াইট স্ট্রাকচার্ড মিনি ব্যাগ",
    price: 3200,
    originalPrice: 3900,
    category: "Mini & Micro Bags",
    color: "Pearl White",
    material: "Embossed Calfskin",
    image: "https://images.unsplash.com/photo-1614179689702-355944cd0918?w=800&auto=format&fit=crop&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=800&auto=format&fit=crop&q=80",
    description: "Compact yet striking structured micro handbag featuring gold monogram charm, top handle, and adjustable crossbody strap.",
    descriptionBn: "ট্রেন্ডি ও আধুনিক মাইক্রো হ্যান্ডব্যাগ। টপ হ্যান্ডেল, সুদৃশ্য গোল্ডেন ব্র্যান্ড লোগো এবং অ্যাডজাস্টেবল বেল্ট।",
    rating: 4.8,
    reviewCount: 31,
    isNewArrival: true,
    isBestSeller: false,
    dimensions: "18cm x 14cm x 8cm"
  },
  {
    id: "raib-backpack-06",
    name: "Sahara Tan Executive Leather Backpack",
    nameBn: "সাহার তান এক্সিকিউটিভ লেদার ব্যাকপ্যাক",
    price: 5200,
    originalPrice: 6500,
    category: "Luxury Backpacks",
    color: "Sahara Tan",
    material: "Full-Grain Waxed Leather",
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80",
    description: "Ergonomic leather backpack designed for modern working women. Padded laptop compartment, anti-theft back pocket, and brass buckles.",
    descriptionBn: "চাকরিজীবী ও ভ্রমণকারী নারীদের জন্য স্পেশাল লেদার ব্যাকপ্যাক। প্যাডেড ল্যাপটপ স্লট ও গোপন পকেটসহ।",
    rating: 4.9,
    reviewCount: 56,
    isNewArrival: false,
    isBestSeller: true,
    dimensions: "38cm x 28cm x 15cm (Fits 14-inch Laptop)"
  }
];
